FORMAT: 1A
HOST: http://core.app/api


# brosa
Polls is a simple API allowing consumers to view polls and vote in them.
## Hello World!! [/message]
### Print the message [GET]
+ Response 200 (application/json)

        {
            "message": "Hello World!!"
        }